### ISSUE TITLE
{question} Need user + pass valid?

### ISSUE THREAD

**Issue by lolminerxmrig** [kh4sh3i/Webmin-CVE#1]
Hi.
Need user + pass valid?

**Comment by kh4sh3i** [comment]
hi
yes. some CVE is for authenticated user. 
you should have valid user and pass

**Comment by lolminerxmrig** [comment]
ok.
thanks.

**Comment by kh4sh3i** [comment]
it is my pleasure

**Comment by lolminerxmrig** [comment]
can share telegram id?

**Comment by kh4sh3i** [comment]
you can send message to my twitter account : https://twitter.com/kh4sh3i_

**Comment by lolminerxmrig** [comment]
twitter no account.
can pv chat ?

**Comment by kh4sh3i** [comment]
pls send your text to my email or linkedin account : 
mail : kh4sh3i@gmail.com
linkedin : @kh4sh3i

**Comment by lolminerxmrig** [comment]
https://keybase.io/lolminerxmrig

**Comment by kh4sh3i** [comment]
you can chat with me in Discord : https://discord.gg/6qcgrS8JzS
